add generate command before cowrie starts

diff --git a/bin/cowrie b/bin/cowrie
--- a/bin/cowrie
+++ b/bin/cowrie
@@ -37,32 +37,34 @@ python_version_warning() {
 }
 
 find_cowrie_directory() {
-    # Determine Cowrie directory
-    if [[ "$0" = /* ]]
+    # Determine Cowrie directory, $0 is a shell variable which holds the name of the currently executing script
+    # it is assumed that Cowrie directory is one level above scripts location
+    if [[ "$0" = /* ]] # if script was invoked with abs path (starting with /)
     then
         COWRIEDIR=$(dirname $0)/..
-    else
-        COWRIEDIR=$(dirname $PWD/$0)/..
+    else # else if script is invoked with relative path
+        COWRIEDIR=$(dirname $PWD/$0)/.. # an absolute path is constructed by combining current working directory and scripts location
     fi
     COWRIEDIR=$(cd ${COWRIEDIR} && pwd -P 2>/dev/null || pwd)
 }
 
 activate_venv() {
     # Activate Python virtual environment
-    VENV="$1"
-    if [ ! -f "$VENV/bin/activate" ]
+    VENV="$1" # takes one arg
+    if [ ! -f "$VENV/bin/activate" ] # VENV is path to virtual env directory, checks if this file exists
     then
-        return 1
+        return 1 # if doesnt exist, returns 1 err code
     fi
-    . $VENV/bin/activate
+    . $VENV/bin/activate # executes the activate script withing virtual env
     return 0
 }
 
 cowrie_status() {
-    # Print status
-    PID=$(cat ${PIDFILE} 2>/dev/null || echo "")
-    if [ -n "$PID" ]; then
-        if ps -p "$PID" 2>&1 >/dev/null; then
+    # Check and Print status
+    PID=$(cat ${PIDFILE} 2>/dev/null || echo "") # reads contents of the file specified by PIDFILE, PIDFILE likely contains the PID of the running cowrie instance
+    # ^if file doesnt exist or there is an error, an empty string is assigned to the PID
+    if [ -n "$PID" ]; then # checks if PID is not empty (if Cowrie PID exists or no)
+        if ps -p "$PID" 2>&1 >/dev/null; then # use ps to check if process with the PID is running
             echo "cowrie is running (PID: ${PID})."
         else
             echo "cowrie is not running (PID: ${PID})."
@@ -74,14 +76,33 @@ cowrie_status() {
     fi
 }
 
+# bin/cowrie generate src/cowrie/shell/generate.py <any input name>
+# This function is to generate all the caching information before starting cowrie honeypot. 
+cowrie_generate() {
+    # call a python script that generates everything 
+    # ***When assigning a value to variable in bash, there should not be any spaces between, PYTHONSCRIPT = "$1"
+    PYTHONSCRIPT="$1" # send in the first argument which would be the python path 
+    python3 "$PYTHONSCRIPT" "$@" # send in the remaining args to the function
+    printf "Python file path is %s.\n" $PYTHONSCRIPT 
+    echo "Python script running..."
+
+    # checking if python script has ran successfully
+    # check if exit status is 0, exit status is $?
+    if [ $? -eq 0 ]; then 
+        echo "Script has successfully run"
+    else
+        echo "Script has failed to run"
+    fi
+}
+
 cowrie_start() {
     # Start Cowrie
-    COWRIEARGS="$*"
-    TWISTEDARGS="${XARGS} --umask=0022 --pidfile=${PIDFILE}"
+    COWRIEARGS="$*" # assigns all arguments to the variable
+    TWISTEDARGS="${XARGS} --umask=0022 --pidfile=${PIDFILE}" # constructs arguments for the twisted command
 
     # Run foreground or background. Foreground has no file log.
     if [ "$COWRIE_STDOUT" = "yes" ]; then
-        TWISTEDARGS="${TWISTEDARGS} -n -l -"
+        TWISTEDARGS="${TWISTEDARGS} -n -l -" # runs in the foreground without file logging
     else
         TWISTEDARGS="${TWISTEDARGS} --logger cowrie.python.logfile.logger"
     fi
@@ -108,6 +129,7 @@ cowrie_start() {
     python_version_warning
 
     # Automatically check if the authbind is enabled or not
+    # authbind is utility that allows non root processes to bind to privileged ports (those below 1024)
     authfile="/etc/authbind/byport/22"
     if [ -z ${AUTHBIND_ENABLED} ] && [ -x "$authfile" ] && command -v authbind >/dev/null; then
         AUTHBIND_ENABLED=yes
@@ -169,7 +191,7 @@ cowrie_force_stop () {
 }
 
 cowrie_usage() {
-    echo "usage: $0 <start|stop|force-stop|restart|status|shell>"
+    echo "usage: $0 <start|stop|force-stop|restart|status|shell|generate>"
 }
 
 # Mostly for Docker use, to quickly get a shell in the container
@@ -209,7 +231,7 @@ key=$1
 shift 1
 case $key in
     stop)
-        cowrie_stop $*
+        cowrie_stop $* # invokes function with any additional arguments ($*)
         ;;
     force-stop)
         cowrie_force_stop $*
@@ -223,6 +245,9 @@ case $key in
         ;;
     status)
         cowrie_status $*
+        ;;
+    generate)
+        cowrie_generate $*
         ;;
     bash)
         cowrie_shell $*
